spring.application.name=app-fisio

# Perfil activo por defecto (dev para local, se sobrescribe en docker con prod)
spring.profiles.active=dev

# Google Calendar Configuration (compartida)
google.calendar.credentials.path=classpath:google-credentials.json
google.calendar.id=app.fisio420@gmail.com

app.security.encryption-secret=ClaveSecretaSuperSeguraDe32Bytes